# Generated by Django 6.0.5 on 2026-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidade',
            name='icone',
            field=models.CharField(default='🛡️', max_length=10),
        ),
        migrations.AddField(
            model_name='vulnerabilidade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vulnerabilidade',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
