# Generated by Django 6.0.5 on 2026-05-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_vulnerabilidade_icone_vulnerabilidade_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoVulnerabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('risco', models.CharField(blank=True, choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo'), ('', 'Não sei')], max_length=1)),
                ('mitigacao', models.TextField(blank=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, default='Anónimo', max_length=100)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vulnerabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='social.vulnerabilidade')),
            ],
        ),
    ]
