# Generated by Django 6.0.5 on 2026-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_sugestaovulnerabilidade_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
